party_id = "1"
pk_i_hash = "0x0b7db6d4b1a09561d86adca9d6e5a36bc9e3497fea91a1b8cf44fedd403d4ce5"
dkg_root = "0x403d4ce2"
ciphertext_hash = "123"
epoch = "1"
d_i_hash = "456"
sk_i = ["1", "2", "3", "4"]
e_i = ["1", "2", "3", "256"]
pk_i_bytes = ["42", "0", "0", "0"]
merkle_path = ["1", "2", "3", "4"]
