ciphertext_hash = "42"
aggregate_pk_hash = "100"
decrypt_nizk_hash = "500"
dkg_root = "200"
epoch = "1"
participant_set_hash = "300"
d_commitment = "0x1a93eceb6b0306e1247aff428dd13ac2b6009e1d8440e976e3698f0d53f9c4aa"
n_participants = "3"
threshold = "2"
committee_party_ids = ["1", "2", "3", "0", "0", "0", "0", "0"]
participant_shares = [
    ["1", "0", "0", "0", "0", "0", "0", "0"],
    ["0", "0", "0", "0", "0", "0", "0", "0"],
    ["0", "0", "0", "0", "0", "0", "0", "0"],
    ["0", "0", "0", "0", "0", "0", "0", "0"],
    ["0", "0", "0", "0", "0", "0", "0", "0"],
    ["0", "0", "0", "0", "0", "0", "0", "0"],
    ["0", "0", "0", "0", "0", "0", "0", "0"],
    ["0", "0", "0", "0", "0", "0", "0", "0"],
]
