#!/usr/bin/env bash
# clean-clone-reproduce.sh — artifact reproduction harness
# Prints steps for reproducing from a clean checkout.
set -euo pipefail

echo "================================================================"
echo "PVTHFHE: Clean-Clone Reproduction Harness"
echo "================================================================"
echo ""
echo "Step 1: Clone repository"
echo "  git clone <repo-url> pvthfhe"
echo "  cd pvthfhe"
echo ""
echo "Step 2: Install toolchain dependencies"
echo "  # Rust (channel from rust-toolchain.toml)"
echo "  curl https://sh.rustup.rs -sSf | sh -s -- -y"
echo "  rustup show  # installs channel pinned in rust-toolchain.toml"
echo ""
echo "  # Foundry"
echo "  curl -L https://foundry.paradigm.xyz | bash"
echo "  foundryup"
echo ""
echo "  # Noir"
echo "  curl -L https://raw.githubusercontent.com/noir-lang/noirup/main/install | bash"
echo "  noirup"
echo ""
echo "  # Barretenberg BB CLI"
echo "  curl -L https://raw.githubusercontent.com/AztecProtocol/aztec-packages/master/barretenberg/bbup/install | bash"
echo "  bbup"
echo ""
echo "  # Just"
echo "  cargo install just"
echo ""
echo "Step 3: Build and test"
echo "  cargo build --workspace"
echo "  just test-all"
echo ""
echo "Step 4: Run gates"
echo "  just phase0-gate"
echo "  just phase1-gate"
echo "  just phase2-gate"
echo "  just phase3-gate"
echo ""
echo "Step 5: Build paper (optional)"
echo "  just paper-build"
echo ""
echo "================================================================"
echo "See REPRODUCING.md for pinned versions and detailed instructions."
echo "================================================================"
