[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
    { access = "read", path = "test/goldens" },
    { access = "read", path = "src" },
    { access = "read-write", path = "../bench/results" },
]
